// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProlistCompany.Leads.Repository;

#nullable disable

namespace ProlistCompany.Leads.Infra.Repository.Migrations
{
    [DbContext(typeof(ContextRepository))]
    partial class ContextRepositoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProlistCompany.Leads.Models.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DataDeInclusao")
                        .HasColumnType("datetimeoffset")
                        .HasColumnOrder(1);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Identificador")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Suburbio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnOrder(999);

                    b.HasKey("Id");

                    b.ToTable("Leads");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5a79530-9126-4152-8840-e2fadb24d044"),
                            Categoria = "Tester",
                            DataDeInclusao = new DateTimeOffset(new DateTime(2024, 2, 4, 9, 31, 40, 103, DateTimeKind.Unspecified).AddTicks(6380), new TimeSpan(0, -3, 0, 0, 0)),
                            Descricao = "Cliente assíduo",
                            Email = "soaresale@bol.com.br",
                            Identificador = 123,
                            Nome = "Alexandre",
                            Preco = 79.140000000000001,
                            Sobrenome = "Soares",
                            Status = 0,
                            Suburbio = "Av Pres. Vargas",
                            Telefone = "+5578915257395"
                        },
                        new
                        {
                            Id = new Guid("7d968401-c2b0-4ee5-b9d7-1b1adbb23ebd"),
                            Categoria = "Tester",
                            DataDeInclusao = new DateTimeOffset(new DateTime(2024, 2, 4, 9, 31, 40, 103, DateTimeKind.Unspecified).AddTicks(6415), new TimeSpan(0, -3, 0, 0, 0)),
                            Email = "soaresale@bol.com.br",
                            Identificador = 312,
                            Nome = "Macário",
                            Preco = 512.0,
                            Sobrenome = "Costa",
                            Status = 0,
                            Suburbio = "Av Pres. Vargas",
                            Telefone = "+5578915257395"
                        },
                        new
                        {
                            Id = new Guid("7219fa73-fe35-4bc6-ba8d-1e92cd356409"),
                            Categoria = "Tester",
                            DataDeInclusao = new DateTimeOffset(new DateTime(2024, 2, 4, 9, 31, 40, 103, DateTimeKind.Unspecified).AddTicks(6466), new TimeSpan(0, -3, 0, 0, 0)),
                            Descricao = "",
                            Email = "soaresale@bol.com.br",
                            Identificador = 835,
                            Nome = "Yuri",
                            Preco = 51356.457399999999,
                            Sobrenome = "Marçal",
                            Status = 0,
                            Suburbio = "Av Pres. Vargas",
                            Telefone = "+5578915257395"
                        },
                        new
                        {
                            Id = new Guid("cd34fe98-1961-471b-a0d7-08ff11d0b622"),
                            Categoria = "Tester",
                            DataDeInclusao = new DateTimeOffset(new DateTime(2024, 2, 4, 9, 31, 40, 103, DateTimeKind.Unspecified).AddTicks(6468), new TimeSpan(0, -3, 0, 0, 0)),
                            Descricao = "Em negociação",
                            Email = "soaresale@bol.com.br",
                            Identificador = 780,
                            Nome = "Ada",
                            Preco = 134211211888766.0,
                            Sobrenome = "Byron",
                            Status = 0,
                            Suburbio = "Av Pres. Vargas",
                            Telefone = "+5578915257395"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
